### ISSUE TITLE
Unreachable Hello Action

### ISSUE THREAD

**Issue by judahnator** [EpistemicPolymath/PolymathicalBot#2]
The second `if` statement below can never be triggered.

https://github.com/EpistemicPolymath/PolymathicalBot/blob/84ef2f6ad624c4da4e4faed2b5ea645b98e96e8e/polybot.js#L44-L52

**Comment by EpistemicPolymath** [comment]
I forgot to tag this issue during my commit, but I fixed the issue like this:
https://github.com/EpistemicPolymath/PolymathicalBot/blob/2a2a25ad447055be4f2b506c5a168682d92372b4/polybot.js#L60-L68
