### ISSUE TITLE
Add "user note" command

### ISSUE THREAD

**Issue by judahnator** [EpistemicPolymath/PolymathicalBot#3]
Was mentioned on stream, could be handy to make a command where the user can provide a note for the broadcaster.

Maybe a `!note {note for broadcaster}` syntax that writes to a CSV file with the timestamp the note was created.

**Comment by EpistemicPolymath** [comment]
I worked on this with the noteDevelopment branch and recently merges. I want to keep this open since I am still working on it, but for now it works well enough. Will continue development.

**Comment by EpistemicPolymath** [comment]
I am satisfied with this for now. I added other issues related to further improvements on this feature.
